version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-volume

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    hostname: graphite
    ports:
      - 80:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8080:8080
      - 8125:8125/udp
      - 8126:8126

  castlemock:
    image: castlemock/castlemock
    container_name: castlemock
    hostname: castlemock
    ports:
      - 8888:8080
    volumes:
      - castlemock-volume

volumes:
  grafana-volume:
    driver: local
  castlemock-volume:
    driver: local
