{
 "title": "Reactive Jammed Architecture",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response time in ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "reactive.jammed.architecture.request-timer.p95"
    }
   ]
  },
  {
   "title": "Input Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "reactive.jammed.architecture.inputs.count"
    }
   ]
  },
  {
   "title": "WS Response Time",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "reactive.jammed.architecture.request-timer.p95"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "reactive.jammed.architecture.requests.count"
    }
   ]
  },
  {
   "title": "Inputs Generation Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "reactive.jammed.architecture.inputs.m1_rate"
    }
   ]
  },
  {
   "title": "Input events/s",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "reactive.jammed.architecture.inputs.m1_rate"
    }
   ]
  },
  {
   "title": "Number of Req/s Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "reactive.jammed.architecture.requests.m1_rate"
    }
   ]
  },
  {
   "title": "WS Req/s",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 15 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "target": "reactive.jammed.architecture.requests.m1_rate"
    }
   ]
  }
 ]
}